---
development:
  database_url: "sqlite://app/db/development.db"
  database_key: "dddddddddddddddddddddddddddddddd"
test:
  database_url: "sqlite://app/db/test.db"
  database_key: "tttttttttttttttttttttttttttttttt"
